version: "3.9"

services:

  db:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=task_manager
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_manager -d task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PYTHONPATH=./
    depends_on:
      db:
        condition: service_healthy